name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    env:
      MUJOCO_GL: osmesa
      DISPLAY: ":0"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env

    - name: Install dependencies
      run: |
        export CPATH=$CONDA_PREFIX/include
        conda install pip --yes
        conda install -c conda-forge freeglut --yes
        conda install -c conda-forge glew --yes
        conda install -c conda-forge mesalib --yes
        conda install -c conda-forge glfw --yes
        conda install -c conda-forge libglu --yes
        conda install -c conda-forge glfw --yes
        conda install -c conda-forge libx11 --yes
        conda install -c conda-forge mesa-libgl-cos7-x86_64 --yes
        conda install -c menpo glfw3 --yes
        conda install -c menpo osmesa --yes
        pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Test with pytest
      run: |
        pytest