name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    env:
      MUJOCO_GL: osmesa
      DISPLAY: ":0"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env

    - name: Install dependencies
      run: |
        conda install -c conda-forge glew
        conda install -c conda-forge mesalib
        conda install -c anaconda mesa-libgl-cos6-x86_64
        conda install -c menpo glfw3
        pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Test with pytest
      run: |
        pytest