name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    env:
      MUJOCO_GL: osmesa
      DISPLAY: ":0"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install libgl1-mesa-dev libxinerama-dev libxcursor-dev libxrandr-dev libxi-dev ninja-build
        sudo apt-get install -y ffmpeg libsm6 libxext6
        sudo apt-get install -y python3-opengl
        sudo apt install libosmesa6 -y
        export CPATH=$CONDA_PREFIX/include
        export C_INCLUDE_PATH=$CONDA_PREFIX/include
        export LIBRARY_PATH=$CONDA_PREFIX/lib
        conda install pip --yes
        pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Test with pytest
      run: |
        pytest